cnt:
  retry:
    MovieService/getNumberOfMoviesForActor/Retry/maxRetries: 10
    MovieService/getNumberOfMoviesForActor/Retry/delay: 10
    MovieService/getNumberOfMoviesForActor/Retry/delayUnit: Seconds