name: CI-Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

concurrency:
  group: ci_${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci-quarkus:
    runs-on: ubuntu-latest
    needs:
      - data-jpa-repository
    steps:
      - run: echo "CI-Build completed!"

  data-jpa-repository:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build
        run: ./gradlew :examples:data-jpa-repository:build
      - name: Upload Test Results
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: test-results_data-jpa-repository
          path: "**/build/reports/tests"
